name: ARM deployment with bicep
on: workflow_dispatch

env:
  LOCATION: "westeurope"                                                  # location for ARM deployment
  BICEP_FILE: "demo.bicep"                                                # bicep filename to deploy
  RESOURCE_GROUP_NAME: "rg-bicep"                                         # resource group name for deployment

jobs:
  build:
    name: ARM Deployment with bicep file
    runs-on: windows-latest
    steps:
    # Checkout: checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. 
    #           source: https://github.com/actions/checkout & https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v2
    
    # Authentication: log on to Azure with the AZURE_CREDENTIALS secret
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    
    # Azure PowerShell: Run inline script
    #                   source: https://github.com/marketplace/actions/azure-powershell-action   
    - name: Run Azure PowerShell script (inline)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Update the Az Module to 5.6.0+
          Update-Module -Name Az -RequiredVersion 5.6.0 -Force -ErrorAction SilentlyContinue

          # Read the GitHub Actions variables
          [string]$githubWorkspace = "${{GITHUB.WORKSPACE}}"

          # Read the environment variables in PowerShell
          [string]$location = [System.Environment]::GetEnvironmentVariable('LOCATION')
          [string]$bicepFile = [System.Environment]::GetEnvironmentVariable('BICEP_FILE')
          [string]$resourcegroupName = [System.Environment]::GetEnvironmentVariable('RESOURCE_GROUP_NAME')
          
          Write-Output ("* BICEP FILE: " + $($bicepFile))
          Write-Output ("* RESOURCE GROUP NAME: " + $($resourcegroupName))
          Write-Output ("* GITHUB_WORKSPACE: " + $($githubWorkspace))

          ## Create a Template Parameter Object (hashtable)
          $objTemplateParameter = @{
            "location" = "$($location)";
            "workSpaceName" = "ws-wvd-bicepdemo";
            "hostpoolName" = "hp-wvd-bicepdemo";
            "appgroupName" = "ag-wvd-bicepdemo";
            "preferredAppGroupType" = "Desktop";
            "hostPoolType" = "pooled";
            "loadbalancertype" = "DepthFirst";
            "appgroupType" = "Desktop";
          }
            
          # Show objTemplateParameter
          $objTemplateParameter
          
          # Temp location for the bicep file that will be used by this script (discarded when runbook is finished)
          $biceptemplateFile = [string]($env:TEMP + "\demo.bicep")
          
          # Storage location for bicep file template
          $templateUrl="https://raw.githubusercontent.com/cognitionIT/AzureWVD/master/Bicep/demo.bicep"
          
          # Retrieve the template file and save it in a temp file location
          Invoke-WebRequest -Uri $templateUrl -OutFile $biceptemplateFile -UseBasicParsing
          
          # Create the resourceGroup
          New-AzResourceGroup -Name $($resourcegroupName) -Location $($location)

          # ARM Template file
          ## Add SessionHosts to existing WVD Hostpool, based on ARM Template
          New-AzResourceGroupDeployment -ResourceGroupName "$($resourcegroupName)" -TemplateFile "$($biceptemplateFile)" -TemplateParameterObject $objTemplateParameter -Verbose
        azPSVersion: 'latest'
