name: ARM deployment with bicep
on: workflow_dispatch

env:
  LOCATION: "westeurope"                   # location for ARM deployment
  BICEP_FILE: "demo.bicep"                 # bicep filename to deploy
  RESOURCE_GROUP_NAME: "rg-bicepdemo"      # resource group name for deployment

jobs:
  build:
    name: ARM Deployment with bicep file
    runs-on: windows-latest
    steps:
    # Action = Checkout: checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. 
    # source: https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v2
    
    # Action = Azure Login: Log on to Azure and authenticate with the AZURE_CREDENTIALS secret
    # source: https://github.com/marketplace/actions/azure-login
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    
    # Action = Azure PowerShell: Run inline script
    # source: https://github.com/marketplace/actions/azure-powershell-action   
    - name: Prep runner with Bicep prereqs using Azure PowerShell
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Create the Bicep install folder
          $installPath = "$env:USERPROFILE\.bicep"
          $installDir = New-Item -ItemType Directory -Path $installPath -Force
          $installDir.Attributes += 'Hidden'
          # Fetch the latest Bicep CLI binary
          (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
          # Add bicep to your PATH
          $currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
          if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
          if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
          # Copy the bicep file to %systemroot%\system32 if it is not already there
          if (-not(Test-Path "$($env:SystemRoot)\System32\bicep.exe"))
          {
            Copy-Item "$installPath\bicep.exe" -Destination "$($env:SystemRoot)\System32" -Force
          }
          # Verify you can now access the 'bicep' command.
          bicep --help
          # Done!
          
          ## Add Az PowerShell Module version 5.6.0 to the runner (if not already on the runner)
          $minAzModuleVersion = '5.6.0'
          if(!(Test-Path "C:\Modules\az_$minAzModuleVersion")) {
            Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
            Save-Module -Path "C:\Modules\az_$minAzModuleVersion" -Name Az -RequiredVersion $minAzModuleVersion -Force -ErrorAction Stop
          }
          $env:PSModulePath = "C:\Modules\az_$($minAzModuleVersion);$($env:PSModulePath)"
          # Check installed versions of Az Module
          Get-InstalledModule -Name Az -AllVersions | sort Version -Descending
        azPSVersion: 'latest'

    # Action = Azure PowerShell: Run inline script
    # source: https://github.com/marketplace/actions/azure-powershell-action   
    - name: Deploy ARM Resources with Bicep & Azure PowerShell
      uses: azure/powershell@v1
      with:
        inlineScript: |
          # Read the GitHub Actions variables
          [string]$githubWorkspace = "${{GITHUB.WORKSPACE}}"

          # Read the environment variables in PowerShell
          [string]$location = [System.Environment]::GetEnvironmentVariable('LOCATION')
          [string]$bicepFile = [System.Environment]::GetEnvironmentVariable('BICEP_FILE')
          [string]$resourcegroupName = [System.Environment]::GetEnvironmentVariable('RESOURCE_GROUP_NAME')
          
          Write-Output ("* BICEP FILE: " + $($bicepFile))
          Write-Output ("* RESOURCE GROUP NAME: " + $($resourcegroupName))
          Write-Output ("* GITHUB_WORKSPACE: " + $($githubWorkspace))

          $namePostFix = $resourcegroupName.Replace("rg-","")

          ## Create a Template Parameter Object (hashtable)
          $objTemplateParameter = @{
            "location" = "$($location)";
            "workSpaceName" = "ws-$($namePostFix)";
            "hostpoolName" = "hp-$($namePostFix)";
            "appgroupName" = "ag-$($namePostFix)";
            "preferredAppGroupType" = "Desktop";
            "hostPoolType" = "pooled";
            "loadbalancertype" = "DepthFirst";
            "appgroupType" = "Desktop";
          }
          ## Show objTemplateParameter
          #$objTemplateParameter
          
          # Location of the bicep file in the local checked-out repo
          $biceptemplateFile = [string]("$($githubWorkspace)" + "\bicep\" + "$($bicepFile)")
          Write-Output ("* BICEP TEMPLATE FILE: " + $($biceptemplateFile))

          # Create the resourceGroup (if it does not yet exist)
          if (!(Get-AzResourceGroup -Name $resourcegroupName -ErrorAction SilentlyContinue)) {
            New-AzResourceGroup -Name $resourcegroupName -Location $location
          }

          # ARM Template file
          ## Deploy resources based on bicep file for ARM Template
          New-AzResourceGroupDeployment -ResourceGroupName $resourcegroupName -TemplateFile $($biceptemplateFile) -TemplateParameterObject $objTemplateParameter -Verbose
        azPSVersion: 'latest'
