name: WVDCreateHostpool
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    # Authentication: log on to Azure with the AZURE_CREDENTIALS secret
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    # Run an inline PowerShell script    
    - name: Run Azure PowerShell script (inline)
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "rg-wvd-resources"
          Write-Output "Testing multi-lined inline script!"
        azPSVersion: '3.1.0'