on: [push]

name: WVDCreateHostpool

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "rg-wvd-resources"
        azPSVersion: '3.1.0'